name: Build Debug APK

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
  pull_request:
    branches: [*]

jobs:
  build_debug_apk:
    name: Build Debug apk
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run tests and build Debug artifacts
        run: |
            ./gradlew test
            ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
            name: app-debug.apk
            path: app/build/outputs/apk/debug/*
