name: Build Debug APK

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
  pull_request:

jobs:
  build_debug_apk:
    name: Build Debug apk
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run tests
        run: ./gradlew test

      - name: Build Debug Apk
        run: ./gradlew assembleDebug assembleRelease --stacktrace

      - name: Upload Debug APK Artifact
        id: artifact-upload-debug
        uses: actions/upload-artifact@v2
        with:
          name: Apks
          path: app/build/outputs/apk/**/*.apk
