name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Build Debug apk
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.8 }

      - name: Run tests and build release artifacts
        run: |
            ./gradlew test
            ./gradlew assembleDebug --stacktrace

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
            name: app-debug.apk
            path: app/build/outputs/apk/debug/app-debug.apk